services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - rtuuy_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - internal

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${DB_ROOT_USER}:${DB_ROOT_PASS}@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASS}
    ports:
      - "8081:8081"
    networks:
      - internal

volumes:
  rtuuy_data:

networks:
  internal:
